/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as OurApproachRouteImport } from './routes/our-approach'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const OurApproachRoute = OurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/our-approach': typeof OurApproachRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/our-approach': typeof OurApproachRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/our-approach': typeof OurApproachRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/industries' | '/our-approach' | '/who-we-are'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/industries' | '/our-approach' | '/who-we-are'
  id: '__root__' | '/' | '/industries' | '/our-approach' | '/who-we-are'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustriesRoute: typeof IndustriesRoute
  OurApproachRoute: typeof OurApproachRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-approach': {
      id: '/our-approach'
      path: '/our-approach'
      fullPath: '/our-approach'
      preLoaderRoute: typeof OurApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustriesRoute: IndustriesRoute,
  OurApproachRoute: OurApproachRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
